#!/usr/bin/env python3
# Sample script that writes to a file
# By Jac 7/18

import os
dir_path = os.path.dirname(os.path.realpath(__file__))

#Open file for writing
f = open(dir_path + "/hackme.txt", "w")

#Prepare Inputs
name = input("What is your name?\n")
color = input("What's your favorite color?\n")
pet = input("What was your first pet's name?\n")
maiden = input("What is your mother's maiden name?\n")
school = input("What elementary school did you attend?\n")

#Write to the file
f.write(name + "\n")
f.write(color + "\n")
f.write(pet + "\n")
f.write(maiden + "\n")
f.write(school)

#Close file
f.close()